### ISSUE TITLE
Does this hax still work at System version 11.1.0-34 ?

### ISSUE THREAD

**Issue by RoestVrijStaal** [shinyquagsire23/supermysterychunkhax#8]
https://www.3dbrew.org/wiki/11.1.0-34#loader

Pokemon Super Mystery Dungeon and other games which have a hax  are mentioned.

**Comment by shinyquagsire23** [comment]
I'm currently working on this, it's 90% done, but needs to be tested on o3DS and actually on an 11.1 system. Also need to port to EUR and JPN.

**Comment by shinyquagsire23** [comment]
Implemented as of 7f6cc3219a2e

**Comment by RoestVrijStaal** [comment]
You rock  :thumbsup::thumbsup::thumbsup:

Also, does the fix also work upstream? Like running on an accidental updated o3DS 11.1.0.0-34 while the hax was updated on an o3DS 11.0.0-33 with 11.0.0-33 as chosen version?

**Comment by shinyquagsire23** [comment]
@RoestVrijStaal At the moment, I'd suggest having another secondary as a backup if possible, because I've gotten some reports that this fails with a yellow screen on 11.1U. If you have two 3DSs with one on <=11.0U and has homebrew and one on 11.1U which needs homebrew, then you're fine since the 11.0 one can install fixes once I figure out what's up. 11.1E has no issues however, it's just slightly unstable on 11.1E.
